services:
  playground:
    image: stackql/stackql-playground:latest
    environment:
      MIDDLEWARE_SCHEME: 'http'
      MIDDLEWARE_HOST: 'api'
      MIDDLEWARE_PORT: '8080'
    ports:
      - "3000:3000"
    depends_on:
      - api

  runner:
    build:
      context: .
      dockerfile: runner.Dockerfile
    working_dir: /home/stackql
    expose:
      - 5444
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - GITHUB_CREDS
      - OKTA_SECRET_KEY
      - NETLIFY_TOKEN
    healthcheck:
      test: ["CMD", "stackql", "--version"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: stackql --pgsrv.port=5444 srv

  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      DB_HOST: runner
      DB_PORT: 5444
      LOGLEVEL: ${LOGLEVEL:-INFO}
    ports:
      - "8080:8080"
    depends_on:
      runner:
        condition: service_healthy