services:
  playground:
    image: stackql/stackql-playground:latest
    environment:
      MIDDLEWARE_SCHEME: 'http'
      MIDDLEWARE_HOST: 'api'
      MIDDLEWARE_PORT: '8080'
    ports:
      - "3000:3000"
    depends_on:
      - api

  runner:
    build:
      context: .
      dockerfile: runner.Dockerfile
    working_dir: /home/stackql
    expose:
      - 5444
    environment:
      - STACKQL_GITHUB_USERNAME
      - STACKQL_GITHUB_PASSWORD
      - AZURE_TENANT_ID
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - GOOGLE_CREDENTIALS
      - DIGITALOCEAN_ACCESS_TOKEN
      - LINODE_TOKEN
      - DATABRICKS_ACCOUNT_ID
      - DATABRICKS_CLIENT_ID
      - DATABRICKS_CLIENT_SECRET
      - CONFLUENT_CLOUD_API_KEY
      - CONFLUENT_CLOUD_API_SECRET
      - OKTA_API_TOKEN
      - NETLIFY_AUTH_TOKEN
    healthcheck:
      test: ["CMD", "stackql", "--version"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: stackql --pgsrv.port=5444 srv

  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      DB_HOST: runner
      DB_PORT: 5444
      LOGLEVEL: ${LOGLEVEL:-INFO}
    ports:
      - "8080:8080"
    depends_on:
      runner:
        condition: service_healthy