@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define Rel_NoRank(e_from,e_to, e_label=" ") Rel_(e_from,e_to, e_label, "-[norank]->")

title StackQL Middleware Container Diagram

Person(admin, "Middleware Admin")
Container(app, "App or Playground", "JAMStack App")

System_Boundary(middleware, "stackql Middleware") {
    Container(lb, "FE LB", "Load Balancer")
    Container(feapi, "Front End API", "Oak")
    Container(adminapi, "Admin API", "Oak")
    Container(stackql, "Runner", "stackql srv")
    ContainerDb(cache, "Results Cache", "Redis")
    ContainerQueue(config, "Shared Config", "Message Queue")
}

Container_Ext(beapi, "API Provider", "REST or GraphQL")

Lay_D(admin, app)
Lay_R(app, lb)
Lay_R(lb, feapi)
Lay_R(feapi, stackql)
Lay_R(stackql, beapi)
Lay_D(adminapi, feapi)
Lay_R(adminapi, config)
Lay_D(feapi, cache)

Rel_Neighbor(admin, adminapi, "updates config")
Rel_Neighbor(adminapi, config, "config")
Rel_R(app, lb, "submits query")
Rel_R(lb, feapi, " ")
Rel_U(cache, feapi, "gets")
Rel_D(feapi, cache, "stores")
Rel_R(feapi, stackql, "submits")
Rel_L(stackql, feapi, "returns")
Rel_R(stackql, beapi, "request")
Rel_L(beapi, stackql, "response")
Rel_D(config, feapi, "config")
Rel_D(config, stackql, "config")
Rel_L(feapi, app, " ")

@enduml