@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define Rel_NoRank(e_from,e_to, e_label=" ") Rel_(e_from,e_to, e_label, "-[norank]->")

title StackQL Docker Compose Architecture

Person(user, "User")

System_Boundary(middleware, "stackql Middleware") {
    Container(playground, "playground", "React/NextJS App")
    Container(api, "api", "deno Oak")
    Container(runner, "runner", "stackql srv")
    ContainerDb(cache, "cache", "Redis")
}

Container_Ext(beapi, "API Provider", "Backend API")

Lay_R(user, playground)
Lay_D(playground, api)
Lay_R(playground, runner)
Lay_D(runner, cache)

Rel_R(user, playground, "localhost:3000")
Rel_R(user, api, "localhost:8080")
Rel_D(playground, api, "localhost:8080")
Rel_R(api, runner, "runner:5444")
Rel_R(runner, beapi, "<i><provider></i>:443")
Rel_D(api, cache, "cache:6379")

@enduml